#
# 同步上游仓库或者清理发布都需要用REPO_TOKEN密匙
#
# 记住，同步上游是不会同步您任何自建文件夹的，所以同步后您要自己对比我现有的文件夹里面diy-part.sh和settings.ini文件有没有更新
#
# REPO_TOKEN密匙制作教程：https://git.io/jm.md
#


name: master同步上游仓库
on:
  workflow_dispatch:
    inputs:
      again-fork:
        description: '[fork-actions]改成[fork],再按[Run workflow]按钮启动,开启同步上游仓库'
        required: false
        default: 'fork'

env:
  BILDYML: synchronization.yml
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  del_runs:
    runs-on: Ubuntu-22.04
    name: master同步上游仓库
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v4
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null 2>&1
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep > /dev/null 2>&1
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: 整理数据
      if: env.REPO_TOKEN && (github.event.inputs.again-fork == 'fork')
      run: |
        cd $GITHUB_WORKSPACE
        git clone -b master https://github.com/jerrykuku/luci-theme-argon shangyou
        git clone -b master https://github.com/${{github.repository}} repogx
        cd shangyou
        FILE_PATH="luasrc/view/themes/argon/footer.htm"
        sed -i '/<a class="luci-link" href="https:\/\/github.com\/openwrt\/luci"/d; /<span class="footer-separator">|<\/span>/d; /<a href="https:\/\/github.com\/jerrykuku\/luci-theme-argon"/d' "$FILE_PATH"

        FOOTER_PATH="luasrc/view/themes/argon/footer_login.htm"
        sed -i '/<a class="luci-link" href="https:\/\/github.com\/openwrt\/luci"/d; /<a href="https:\/\/github.com\/jerrykuku\/luci-theme-argon"/d' "$FOOTER_PATH"
        cd ..
        
        rm -rf repogx/*
        cp -rf shangyou/* repogx/
        
    - name: 同步上游仓库
      if: env.REPO_TOKEN && (github.event.inputs.again-fork == 'fork')
      run: |
        cd $GITHUB_WORKSPACE
        chmod -R 775 repogx
        cd repogx
        git add .
        git commit -m "up"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:master
